### ISSUE TITLE
json_body does not exist

### ISSUE THREAD

**Issue by jkobject** [broadinstitute/dalmatian#17]
wrong variable used in `wmanager.py` in line 435. 
Need to replace `json_body` with `config`

**Comment by agraubert** [comment]
Yes, this was fixed in 5db5bc0, which is incorporated in 0.0.10

I apologize for the recent instability in dalmatian and lapdog. The recent changeset was significant and there were still bugs left behind. In the future I'm planning on improving the testing process so the packages remain more stable
