### ISSUE TITLE
WorkspaceManager.get_pair_sets() doesn't work

### ISSUE THREAD

**Issue by jcha40** [broadinstitute/dalmatian#7]
This is the error I get.
pair_set_ids = [i['name'] for i in r]
TypeError: string indices must be integers

**Comment by francois-a** [comment]
This should be fixed in v0.0.4. Can you please confirm that this is the version you're using?

**Comment by jcha40** [comment]
I was using v0.0.3. I have updated to v0.0.4 and the issue is fixed; thank you.
